import { invoke } from '@tauri-apps/api/core'
import { listen, type UnlistenFn } from '@tauri-apps/api/event'
import { open } from '@tauri-apps/plugin-dialog'
import { openUrl, revealItemInDir } from '@tauri-apps/plugin-opener'
import type { Inventory, Progress, StoreStats } from './types'

/** False when the UI runs in a plain browser (vite dev without Tauri). */
export const inTauri = typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window

// Browser-only fallback: a saved real scan, so the UI can be worked on
// without the desktop shell. Generated by the survey example with --json.
async function devInventory(): Promise<Inventory | null> {
  try {
    const res = await fetch('/dev-inventory.json')
    return res.ok ? ((await res.json()) as Inventory) : null
  } catch {
    return null
  }
}

export async function lastInventory(root: string): Promise<Inventory | null> {
  if (!inTauri) return devInventory()
  return invoke<Inventory | null>('last_inventory', { root })
}

export async function scanAndCheck(root: string, refresh: boolean): Promise<Inventory> {
  if (!inTauri) {
    const inv = await devInventory()
    if (!inv) throw new Error('No dev inventory available outside the desktop app')
    return inv
  }
  return invoke<Inventory>('scan_and_check', { root, refresh })
}

export async function storeStats(): Promise<StoreStats | null> {
  if (!inTauri) return null
  return invoke<StoreStats>('store_stats')
}

export async function clearCache(): Promise<void> {
  if (inTauri) await invoke('clear_cache')
}

export async function onProgress(handler: (p: Progress) => void): Promise<UnlistenFn> {
  if (!inTauri) return () => {}
  return listen<Progress>('mehen://progress', (e) => handler(e.payload))
}

export async function pickFolder(current: string): Promise<string | null> {
  if (!inTauri) return null
  const picked = await open({ directory: true, defaultPath: current, title: 'Choose a folder to scan' })
  return typeof picked === 'string' ? picked : null
}

export async function reveal(path: string) {
  if (inTauri) await revealItemInDir(path)
}

export async function openInEditor(path: string) {
  if (inTauri) await invoke('open_in_editor', { path })
}

export async function openLink(url: string) {
  if (inTauri) await openUrl(url)
  else window.open(url, '_blank', 'noopener')
}
